name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        KEY: ${{ secrets.KEY }}
        REIGION: ${{ secrets.REIGION }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        KEY: ${{ secrets.KEY }}
        REIGION: $ {{ secrets.REIGION }} 
        BRANCH: gh-pages
        FOLDER: build
